### ISSUE TITLE
multi-classification

### ISSUE THREAD

**Issue by twsha** [CVer-Yang/RCFSNet#2]
Can this model be used for multi-classification of remote sensing images

**Comment by CVer-Yang** [comment]
Technology is feasible. You only need to modify the network classes. But these designs are aimed at extracting road features. In addition, you can pay attention to MACUnet.

**Comment by twsha** [comment]
> Technology is feasible. You only need to modify the network classes. But these designs are aimed at extracting road features. In addition, you can pay attention to MACUnet.
thank you
